---

- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - gnupg

- name: Create keyrings folder
  ansible.builtin.file:
    path: "{{ containerd_apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add Docker`s official GPG key
  ansible.builtin.get_url:
    url: "{{ containerd_apt_gpg_url }}"
    dest: "{{ containerd_apt_keyrings_dir }}/{{ containerd_apt_keyrings_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch={{ containerd_arch }} signed-by={{ containerd_apt_keyrings_dir }}/{{ containerd_apt_keyrings_file }}] {{ containerd_apt_source }} {{ ansible_facts['distribution_release'] }} stable"
    state: present

- name: Install containerd
  ansible.builtin.apt:
    name:
      - containerd.io
    update_cache: true
    state: present
