---

- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl

- name: Create keyrings folder
  ansible.builtin.file:
    path: "{{ containerd_apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add Docker`s official GPG key
  ansible.builtin.apt_key:
    url: "{{ containerd_apt_gpg_url }}"
    keyring: "{{ containerd_apt_keyrings_dir }}/{{ containerd_apt_keyrings_file }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch={{ containerd_arch }} signed-by={{ containerd_apt_keyrings_dir }}/{{ containerd_apt_keyrings_file }}] {{ containerd_apt_source }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - containerd.io
    update_cache: true
    state: present
