---

- name: Create keyrings folder
  ansible.builtin.file:
    path: "{{ crio_apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add cri-o apt repository key.
  ansible.builtin.get_url:
    url: "{{ crio_apt_gpg_url }}"
    dest: "{{ crio_apt_keyrings_dir }}/{{ crio_apt_keyrings_file }}"

- name: Add cri-o repository
  ansible.builtin.apt_repository:
    filename: cri-0
    repo: "deb [arch={{ crio_arch }} signed-by={{ crio_apt_keyrings_dir }}/{{ crio_apt_keyrings_file }}] {{ crio_apt_source }} /"
    state: present

- name: Install cri-o
  ansible.builtin.apt:
    name:
      - cri-o
    update_cache: true
    state: present
