---

- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg

- name: Create keyrings folder
  ansible.builtin.file:
    path: "{{ gvisor_apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add gVisor`s official GPG key
  ansible.builtin.get_url:
    url: "{{ gvisor_apt_gpg_url }}"
    dest: "{{ gvisor_apt_keyrings_dir }}/{{ gvisor_apt_keyrings_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Add gVisor repository
  ansible.builtin.apt_repository:
    filename: gvisor
    repo: "deb [arch={{ host_architecture }} signed-by={{ gvisor_apt_keyrings_dir }}/{{ gvisor_apt_keyrings_file }}] {{ gvisor_apt_source }} release main"
    state: present

- name: Install gVisor
  ansible.builtin.apt:
    name:
      - runsc
    update_cache: true
    state: present
