---
sysctl_k8s_file: /etc/sysctl.d/k8s.conf
sysctl_inotify_file: /etc/sysctl.d/inotify.conf
sysctl_inotify_max_user_watches: 524288
sysctl_inotify_max_user_instances: 16384

kubernetes_server: ""
kubernetes_server_ip: ""

ipv6_enabled: false
